version: '3.8'

services:

  database:
    image: mysql
    environment:  
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: samplewallet
      MYSQL_USER: loona
      MYSQL_PASSWORD: secret
  adminer:
    image: adminer
    ports:
      - 8081:8080

  redis:
    image: redis
    ports:
      - 6379:6379

  php-server:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - redis

  web-server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8011:80"
    depends_on:
      - php-server